spring.datasource.username=postgres
spring.datasource.password=102030
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/hopefood

# Cria as tabelas
#spring.jpa.generate-ddl=true

# Mostra as SQLs de consulta
spring.jpa.show-sql=true

# Deleta e recria as tabelas toda vez que a aplicação é levantada
#spring.jpa.hibernate.ddl-auto=create

# Pool de conexões  
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=10000

# Criar um script de DDL das tabelas
#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

# Lança um erro quando a propriedade da entidade não existe
spring.jackson.deserialization.fail-on-unknown-properties=true

# Lança um erro quando a propriedade da entidade está sendo ignorada pelo @JsonIgnore
spring.jackson.deserialization.fail-on-ignored-properties=true

# Lança um erro quando o recurso não for encontrado
spring.mvc.throw-exception-if-no-handler-found=true

#Desabilita o resource handler do Spring, sua função é servir os arquivos na pasta resources/static
spring.web.resources.add-mappings=false
