create table produto (
  id int8 generated by default as identity,
  ativo boolean not null,
  descricao varchar(255) not null,
  nome varchar(255) not null,
  preco numeric(19, 2) not null,
  restaurante_id int8 not null,
  data_atualizacao timestamp not null,
  data_cadastro timestamp not null,

  primary key (id)
);