create table restaurante (
  id int8 generated by default as identity,
  data_atualizacao timestamp not null,
  data_cadastro timestamp not null,
  endereco_bairro varchar(255),
  endereco_cep varchar(255),
  endereco_complemento varchar(255),
  endereco_logradouro varchar(255),
  endereco_numero varchar(255),
  nome varchar(255) not null,
  taxa_frete numeric(19, 2) not null,
  cozinha_id int8 not null,
  endereco_cidade_id int8,

  primary key (id)
);