create table usuario (
  id int8 generated by default as identity,
  data_atualizacao timestamp not null,
  data_cadastro timestamp not null,
  email varchar(255) not null,
  nome varchar(255) not null,
  senha varchar(255) not null,

  primary key (id)
);